export default [
  {
    id: 12346,
    category: 'Devellopeur',
    name: 'Simon Delaporte',
    picture: 'https://cdn4.iconfinder.com/data/icons/avatars-xmas-giveaway/128/batman_hero_avatar_comics-512.png',
    available: true,
    stock: '',
    price: 'Back',
    unit: 'Lead dev Back',
  },
  {
    id: 12347,
    category: 'légume',
    categorySlug: 'legume-tiges',
    familly: 'légume tiges',
    name: 'Justine Strescher',
    slug: 'Asperge',
    picture: 'https://cdn4.iconfinder.com/data/icons/avatars-xmas-giveaway/128/female_woman_avatar_portrait_1-512.png',
    description: 'Délicieuse pomme de terre de saison',
    longDescription: 'Délicieuse pomme de terre de saison du jardin',
    available: true,
    stock: 45,
    price: 'Back',
    unit: 'Référente technique git / Product Owner',
  },
  {
    id: 12348,
    category: 'légume',
    categorySlug: 'legume-tiges',
    familly: 'légume tiges',
    name: 'Hugo Le Cloerec',
    slug: 'Pomme-de-terre',
    picture: 'https://cdn4.iconfinder.com/data/icons/avatars-xmas-giveaway/128/breaking_bad_chemisrty_avatar_heisenberg-512.png',
    description: 'Délicieuse pomme de terre de saison',
    longDescription: 'Délicieuse pomme de terre de saison du jardin',
    available: true,
    stock: 45,
    price: 'Front',
    unit: 'Lead dev Front',
  },
  {
    id: 12349,
    category: 'légume',
    categorySlug: 'legume-tubercule',
    familly: 'légume tubercule',
    name: 'Clément Le Lec',
    slug: 'Radis',
    picture: 'https://cdn4.iconfinder.com/data/icons/avatars-xmas-giveaway/128/indian_native_boy_kid-512.png',
    description: 'Délicieuse pomme de terre de saison',
    longDescription: 'Délicieuse pomme de terre de saison du jardin',
    available: true,
    stock: 45,
    price: 'Front',
    unit: 'Scrum Master',
  },
];
