export default [
  {
    id: 1,
    name: 'Les légumes fleurs',
    slug: 'Les-legumes-fleurs',
    picture: 'https://images.pexels.com/photos/4750382/pexels-photo-4750382.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260dpr=1&w=500',
    available: true,
  },
  {
    id: 2,
    name: 'Les légumes feuilles',
    slug: 'Les-legumes-feuiles',
    picture: 'https://images.pexels.com/photos/7511805/pexels-photo-7511805.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    available: false,
  },
  {
    id: 3,
    name: 'Les légumes fruits',
    slug: 'Les-legumes-fruits',
    picture: 'https://media.istockphoto.com/photos/two-fresh-zucchini-isolated-picture-id94929472?k=20&m=94929472&s=612x612&w=0&h=kcnUXOMRsOIxdFNZJ_7VW2JC6dqwDlyDJayGMavU9rw=',
    available: true,
  },
  {
    id: 4,
    name: 'Les légumes à bulbe',
    slug: 'Les-legumes-bulbes',
    picture: 'https://images.pexels.com/photos/6316528/pexels-photo-6316528.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    available: true,
  },
  {
    id: 5,
    name: 'Les légumes tubercules',
    slug: 'Les-legumes-tubercules',
    picture: 'https://images.pexels.com/photos/3094074/pexels-photo-3094074.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    available: false,
  },
  {
    id: 6,
    name: 'Les légumes graines',
    slug: 'Les-legumes-graines',
    picture: 'https://images.pexels.com/photos/625422/pexels-photo-625422.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    available: false,
  },
  {
    id: 7,
    name: 'Les légumes racine',
    slug: 'Les-legumes-racine',
    picture: 'https://images.pexels.com/photos/1656663/pexels-photo-1656663.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    available: true,
  },
  {
    id: 8,
    name: 'Les légumes tiges',
    slug: 'Les-legumes-tiges',
    picture: 'https://images.pexels.com/photos/42165/pexels-photo-42165.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    available: false,
  },
];
