export default [
  {
    id: 12345,
    category: 'légume fruit',
    categorySlug: 'legume-fruit',
    name: 'Courgette',
    slug: 'Courgette',
    picture: 'https://media.istockphoto.com/photos/two-fresh-zucchini-isolated-picture-id94929472?k=20&m=94929472&s=612x612&w=0&h=kcnUXOMRsOIxdFNZJ_7VW2JC6dqwDlyDJayGMavU9rw=',
    description: 'Délicieuse courgettes de saison',
    longDescription: 'delicieuse courgettes de saison du jardin',
    available: false,
    stock: 35,
    price: 3.40,
    unit: 'Kg',
  },
  {
    id: 12346,
    category: 'légume',
    categorySlug: 'legume-fruit',
    familly: 'légume tubercule',
    name: 'Pomme de terre',
    slug: 'Pomme-de-terre',
    picture: 'https://images.pexels.com/photos/7774212/pexels-photo-7774212.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    description: 'Délicieuse pomme de terre de saison',
    longDescription: 'Délicieuse pomme de terre de saison du jardin',
    available: true,
    stock: 45,
    price: 4.00,
    unit: 'Kg',
  },
  {
    id: 12346,
    category: 'légume',
    categorySlug: 'legume-fruit',
    familly: 'légume tubercule',
    name: 'Pomme de terre',
    slug: 'Pomme-de-terre',
    picture: 'https://images.pexels.com/photos/7774212/pexels-photo-7774212.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    description: 'Délicieuse pomme de terre de saison',
    longDescription: 'Délicieuse pomme de terre de saison du jardin',
    available: false,
    stock: 45,
    price: 4.00,
    unit: 'Kg',
  },
  {
    id: 12346,
    category: 'légume',
    categorySlug: 'legume-fruit',
    familly: 'légume tubercule',
    name: 'Pomme de terre',
    slug: 'Pomme-de-terre',
    picture: 'https://images.pexels.com/photos/7774212/pexels-photo-7774212.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    description: 'Délicieuse pomme de terre de saison',
    longDescription: 'Délicieuse pomme de terre de saison du jardin',
    available: false,
    stock: 45,
    price: 4.00,
    unit: 'Kg',
  },
  {
    id: 12346,
    category: 'légume',
    categorySlug: 'legume-fruit',
    familly: 'légume tubercule',
    name: 'Pomme de terre',
    slug: 'Pomme-de-terre',
    picture: 'https://images.pexels.com/photos/7774212/pexels-photo-7774212.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    description: 'Délicieuse pomme de terre de saison',
    longDescription: 'Délicieuse pomme de terre de saison du jardin',
    available: false,
    stock: 45,
    price: 4.00,
    unit: 'Kg',
  },
];
