export default [
  {
    id: 12345,
    category: 'légume fruit',
    title: 'Courgette',
    slug: 'Courgette',
    picture: 'https://images.pexels.com/photos/3375263/pexels-photo-3375263.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    description: 'delicieuse courgettes de saison',
    longDescription: 'delicieuse courgettes de saison du jardin',
    available: false,
    stock: 35,
    price: 1.20,
    kiloPrice: 3.40,
  },
  // {
  //   id: 12346,
  //   category: 'légume',
  //   familly: 'légume tubercule',
  //   title: 'Pomme de terre',
  //   slug: 'Pomme de terre',
  //   picture: 'https://images.pexels.com/photos/7774212/pexels-photo-7774212.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
  //   description: 'Délicieuse pomme de terre de saison',
  //   longDescription: 'Délicieuse pomme de terre de saison du jardin',
  //   available: true,
  //   stock: 45,
  //   unitPrice: 0.33,
  //   kiloPrice: 4.00,
  // },
];
