export default [
  {
    id: 12345,
    category: 'légume fruit',
    categorySlug: 'les-legumes-fruits',
    familly: 'légume fruit',
    name: 'Courgette',
    slug: 'Courgette',
    picture: 'https://media.istockphoto.com/photos/two-fresh-zucchini-isolated-picture-id94929472?k=20&m=94929472&s=612x612&w=0&h=kcnUXOMRsOIxdFNZJ_7VW2JC6dqwDlyDJayGMavU9rw=',
    description: 'Délicieuse courgettes de saison',
    longDescription: 'delicieuse courgettes de saison du jardin',
    available: true,
    stock: 35,
    price: 3.40,
    unit: 'Kg',
  },
  {
    id: 12346,
    category: 'légume',
    categorySlug: 'les-legumes-feuiles',
    familly: 'légume feuille',
    name: 'Batavia',
    slug: 'Batavia',
    picture: 'https://media.istockphoto.com/photos/batavia-picture-id973905078?k=20&m=973905078&s=612x612&w=0&h=hK-VJbZbxZ1hOJQGIdhbfFiC4YMy2f_BbhX25wGxUc4=',
    description: 'Délicieuse batavia de saison',
    longDescription: 'Délicieuse batavia de saison du jardin',
    available: true,
    stock: 45,
    price: 1.5,
    unit: 'unité',
  },
  {
    id: 12347,
    category: 'légume',
    categorySlug: 'les-legumes-tiges',
    familly: 'légumes tiges',
    name: 'Asperge',
    slug: 'Asperge',
    picture: 'https://media.istockphoto.com/photos/green-asparagus-sticks-picture-id1084123600?k=20&m=1084123600&s=612x612&w=0&h=xR1UsRvTEcQ929NRfAixiejh52YK4NvtNLyZUiEhrrE=',
    description: 'Délicieuse pomme de terre de saison',
    longDescription: 'Délicieuse pomme de terre de saison du jardin',
    available: true,
    stock: 45,
    price: 8.50,
    unit: 'Kg',
  },
  {
    id: 12348,
    category: 'légume',
    categorySlug: 'les-legumes-racine',
    familly: 'légumes racine',
    name: 'Pomme de terre',
    slug: 'Pomme-de-terre',
    picture: 'https://media.istockphoto.com/photos/three-potatoes-picture-id157430678?k=20&m=157430678&s=612x612&w=0&h=dfYLuPYwA50ojI90hZ4jCgKZd5TGnqf24UCVBszoZIA=',
    description: 'Délicieuse pomme de terre de saison',
    longDescription: 'Délicieuse pomme de terre de saison du jardin',
    available: false,
    stock: 45,
    price: 4.00,
    unit: 'Kg',
  },
  {
    id: 12349,
    category: 'légume',
    categorySlug: 'les-legumes-tubercules',
    familly: 'légume tubercule',
    name: 'Radis',
    slug: 'Radis',
    picture: 'https://media.istockphoto.com/photos/bunch-of-radishes-picture-id471245003?k=20&m=471245003&s=612x612&w=0&h=J_43NSZFYxVze33sPgvJiXVghqzl9m8aA2exEH0Fifk=',
    description: 'Délicieuse pomme de terre de saison',
    longDescription: 'Délicieuse pomme de terre de saison du jardin',
    available: false,
    stock: 45,
    price: 3.50,
    unit: 'Kg',
  },
  {
    id: 12350,
    category: 'légume fruit',
    categorySlug: 'les-legumes-bulbes',
    familly: 'légume bulbe',
    name: 'Courgette',
    slug: 'Courgette',
    picture: 'https://media.istockphoto.com/photos/two-fresh-zucchini-isolated-picture-id94929472?k=20&m=94929472&s=612x612&w=0&h=kcnUXOMRsOIxdFNZJ_7VW2JC6dqwDlyDJayGMavU9rw=',
    description: 'Délicieuse courgettes de saison',
    longDescription: 'delicieuse courgettes de saison du jardin',
    available: true,
    stock: 35,
    price: 3.40,
    unit: 'Kg',
  },
  {
    id: 12351,
    category: 'légume',
    categorySlug: 'les-legumes-graines',
    familly: 'légume graine',
    name: 'Batavia',
    slug: 'Batavia',
    picture: 'https://media.istockphoto.com/photos/batavia-picture-id973905078?k=20&m=973905078&s=612x612&w=0&h=hK-VJbZbxZ1hOJQGIdhbfFiC4YMy2f_BbhX25wGxUc4=',
    description: 'Délicieuse batavia de saison',
    longDescription: 'Délicieuse batavia de saison du jardin',
    available: true,
    stock: 45,
    price: 1.5,
    unit: 'unité',
  },
  {
    id: 12352,
    category: 'légume',
    categorySlug: 'les-legumes-racine',
    familly: 'légumes racine',
    name: 'Asperge',
    slug: 'Asperge',
    picture: 'https://media.istockphoto.com/photos/green-asparagus-sticks-picture-id1084123600?k=20&m=1084123600&s=612x612&w=0&h=xR1UsRvTEcQ929NRfAixiejh52YK4NvtNLyZUiEhrrE=',
    description: 'Délicieuse pomme de terre de saison',
    longDescription: 'Délicieuse pomme de terre de saison du jardin',
    available: true,
    stock: 45,
    price: 8.50,
    unit: 'Kg',
  },
  {
    id: 12352,
    category: 'légume',
    categorySlug: 'les-legumes-fleurs',
    familly: 'légumes fleurs',
    name: 'Asperge',
    slug: 'Asperge',
    picture: 'https://media.istockphoto.com/photos/green-asparagus-sticks-picture-id1084123600?k=20&m=1084123600&s=612x612&w=0&h=xR1UsRvTEcQ929NRfAixiejh52YK4NvtNLyZUiEhrrE=',
    description: 'Délicieuse pomme de terre de saison',
    longDescription: 'Délicieuse pomme de terre de saison du jardin',
    available: true,
    stock: 45,
    price: 8.50,
    unit: 'Kg',
  },
];
